### ISSUE TITLE
Lumen 8 / Laravel 8 support

### ISSUE THREAD

**Issue by EntonoX** [Douglasdc3/laravel-kong#19]
I created a pull request to make the package compatible with Lumen 8 / Laravel 8. I Also tested the package with the latest Kong 2.x version to verify functionality. All seems fine so i added this support in the readme file.

@Douglasdc3  Can you please merge this and update packagist?

**Comment by Douglasdc3** [comment]
Released v1.2 with laravel 8 support

**Comment by EntonoX** [comment]
@Douglasdc3 Awesome! thanks for the quick response :)
