### ISSUE TITLE
JWT plugin 1.0.x compatibility

### ISSUE THREAD

**Issue by EntonoX** [Douglasdc3/laravel-kong#9]
I just tested with: 
- Kong v1.2.x 
- JWT plugin v1.0.x 

and noticed that creating a consumer JWT doesn't work. I'm planning to make a pull request for it. But it brakes compatibility with JWT 0.1.x  versions. So i think its necessary to create a new tag for it and mention in the readme that this version is only compatible with JWT 1.0.x

**Comment by EntonoX** [comment]
@Douglasdc3 I created a pull request for this issue. This will brake support for older JWT plugin so i added a compatibility table in the readme file. Seems to me a new version tag (v.2.4.0) is needed when this branch is merged.

**Comment by Douglasdc3** [comment]
Thanks! Much appreciated!

Released this as the first stable version on the package.
